spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingmall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234
  sql:
    init:
      mode: never  # never, always
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: update   # create, update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true  # Hibernate 이후 data.sql 실행

  profiles:
    active: local

server:
  port: 8080